version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      browser-test-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /crates/yomu-shell/gen/android
    schedule:
      interval: weekly
    groups:
      android-dependencies:
        patterns: ["*"]
