//! Reading progress as an append-only journal.
//!
//! Every position change is a fact: "on device D, manga M was at chapter C
//! page P at time T". The current position is the merge of all facts:
//! **latest `at` wins, event id (UUIDv7, time-ordered) breaks ties**.
//!
//! This is deliberately the hard-to-refactor part designed first: an
//! offline client keeps its own journal while disconnected and pushes it on
//! reconnect; the same merge rule produces the same result everywhere, so
//! server and clients never diverge. Page-level granularity only (per the
//! product decision) — no per-panel tracking.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProgressEvent {
    /// UUIDv7, generated by whichever device observed the event.
    pub id: Uuid,
    pub manga_id: Uuid,
    pub chapter_id: Uuid,
    /// 0-based page within the chapter.
    pub page: u32,
    /// Device that produced the event (e.g. `"web"`, `"phone"`).
    pub device: String,
    pub at: DateTime<Utc>,
}

/// Merged current position for a manga.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Position {
    pub chapter_id: Uuid,
    pub page: u32,
    pub at: DateTime<Utc>,
}

/// Pick the winning event according to the journal merge rule.
/// Works on any subset; merging partial journals is associative.
pub fn merge_position<'a, I>(events: I) -> Option<&'a ProgressEvent>
where
    I: IntoIterator<Item = &'a ProgressEvent>,
{
    events
        .into_iter()
        .max_by(|a, b| a.at.cmp(&b.at).then_with(|| a.id.cmp(&b.id)))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ev(id: u128, at_secs: i64, page: u32) -> ProgressEvent {
        ProgressEvent {
            id: Uuid::from_u128(id),
            manga_id: Uuid::from_u128(1),
            chapter_id: Uuid::from_u128(2),
            page,
            device: "test".into(),
            at: DateTime::from_timestamp(at_secs, 0).unwrap(),
        }
    }

    #[test]
    fn latest_wins_and_id_breaks_ties() {
        let events = [ev(1, 100, 4), ev(2, 200, 9), ev(3, 200, 7)];
        // 2 and 3 share a timestamp; higher id (3) wins deterministically.
        assert_eq!(merge_position(&events).unwrap().page, 7);

        // Merging winners of partial journals gives the same result
        // (associativity — what offline reconciliation relies on).
        let (a, b) = events.split_at(1);
        let partial = [
            merge_position(a).unwrap().clone(),
            merge_position(b).unwrap().clone(),
        ];
        assert_eq!(merge_position(&partial).unwrap().page, 7);
    }
}
