//! Reading progress as an append-only journal.
//!
//! Every position change is a fact: "on device D, publication M was at unit C
//! location L at time T". The current position is the merge of all facts:
//! **latest `at` wins, event id (UUIDv7, time-ordered) breaks ties**.
//!
//! This is deliberately the hard-to-refactor part designed first: an
//! offline client keeps its own journal while disconnected and pushes it on
//! reconnect; the same merge rule produces the same result everywhere, so
//! server and clients never diverge. Fixed layouts use page indices;
//! reflowable text uses resource-relative progression, not synthetic pages.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProgressEvent {
    /// UUIDv7, generated by whichever device observed the event.
    pub id: Uuid,
    #[serde(rename = "manga_id")]
    pub publication_id: Uuid,
    #[serde(rename = "chapter_id")]
    pub unit_id: Uuid,
    /// 0-based page within the unit.
    pub page: u32,
    /// Resource-relative progression for reflowable text, in [0, 1]. Additive
    /// to the legacy page wire field; fixed-layout events leave it absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progression: Option<f64>,
    /// Device that produced the event (e.g. `"web"`, `"phone"`).
    pub device: String,
    pub at: DateTime<Utc>,
}

/// Merged current position for a publication (was `Position`). Wire shape
/// preserves `{chapter_id, page, at}` with optional `progression`:
/// `locations` flattens and the enum is untagged.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Locator {
    #[serde(rename = "chapter_id")]
    pub unit_id: Uuid,
    #[serde(flatten)]
    pub locations: Locations,
    pub at: DateTime<Utc>,
}

/// Where within a resource: a fixed page, or reflowable progression. The
/// progression variant comes first so additive EPUB payloads with the legacy
/// `page: 0` fallback do not accidentally deserialize as page locations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Locations {
    Progression { progression: f64, page: u32 },
    Page { page: u32 },
}

impl Locator {
    /// The page for image-based kinds.
    pub fn page(&self) -> u32 {
        match self.locations {
            Locations::Page { page } | Locations::Progression { page, .. } => page,
        }
    }

    pub fn progression(&self) -> Option<f64> {
        match self.locations {
            Locations::Progression { progression, .. } => Some(progression),
            Locations::Page { .. } => None,
        }
    }

    pub fn query(&self) -> String {
        match self.progression() {
            Some(value) => format!("progression={value}"),
            None => format!("page={}", self.page()),
        }
    }
}

impl ProgressEvent {
    pub fn locations(&self) -> Locations {
        match self.progression {
            Some(progression) => Locations::Progression {
                progression,
                page: self.page,
            },
            None => Locations::Page { page: self.page },
        }
    }
}

/// Pick the winning event according to the journal merge rule.
/// Works on any subset; merging partial journals is associative.
pub fn merge_position<'a, I>(events: I) -> Option<&'a ProgressEvent>
where
    I: IntoIterator<Item = &'a ProgressEvent>,
{
    events
        .into_iter()
        .max_by(|a, b| a.at.cmp(&b.at).then_with(|| a.id.cmp(&b.id)))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ev(id: u128, at_secs: i64, page: u32) -> ProgressEvent {
        ProgressEvent {
            id: Uuid::from_u128(id),
            publication_id: Uuid::from_u128(1),
            unit_id: Uuid::from_u128(2),
            page,
            progression: None,
            device: "test".into(),
            at: DateTime::from_timestamp(at_secs, 0).unwrap(),
        }
    }

    #[test]
    fn latest_wins_and_id_breaks_ties() {
        let events = [ev(1, 100, 4), ev(2, 200, 9), ev(3, 200, 7)];
        // 2 and 3 share a timestamp; higher id (3) wins deterministically.
        assert_eq!(merge_position(&events).unwrap().page, 7);

        // Merging winners of partial journals gives the same result
        // (associativity — what offline reconciliation relies on).
        let (a, b) = events.split_at(1);
        let partial = [
            merge_position(a).unwrap().clone(),
            merge_position(b).unwrap().clone(),
        ];
        assert_eq!(merge_position(&partial).unwrap().page, 7);
    }

    #[test]
    fn progression_wire_roundtrips_without_becoming_a_page_location() {
        let event = ProgressEvent {
            progression: Some(0.375),
            ..ev(1, 100, 0)
        };
        let locator = Locator {
            unit_id: event.unit_id,
            locations: event.locations(),
            at: event.at,
        };
        let json = serde_json::to_value(&locator).unwrap();
        assert_eq!(json["page"], 0, "old clients retain a safe fallback");
        assert_eq!(json["progression"], 0.375);
        assert_eq!(serde_json::from_value::<Locator>(json).unwrap(), locator);
        assert_eq!(locator.query(), "progression=0.375");
        let json = serde_json::to_value(ev(1, 100, 0)).unwrap();
        assert!(
            json.get("progression").is_none(),
            "legacy events remain unchanged"
        );
    }

    #[test]
    fn locator_wire_is_1x_position() {
        let json = r#"{"chapter_id":"00000000-0000-0000-0000-000000000002","page":7,"at":"2026-01-01T00:00:00Z"}"#;
        let l: Locator = serde_json::from_str(json).unwrap();
        assert_eq!(l.page(), 7);
        let out = serde_json::to_value(&l).unwrap();
        assert_eq!(out["chapter_id"], "00000000-0000-0000-0000-000000000002");
        assert_eq!(out["page"], 7);
        assert!(out.get("locations").is_none());
    }
}
