//! Reading progress as an append-only journal.
//!
//! Every position change is a fact: "on device D, manga M was at chapter C
//! page P at time T". The current position is the merge of all facts:
//! **latest `at` wins, event id (UUIDv7, time-ordered) breaks ties**.
//!
//! This is deliberately the hard-to-refactor part designed first: an
//! offline client keeps its own journal while disconnected and pushes it on
//! reconnect; the same merge rule produces the same result everywhere, so
//! server and clients never diverge. Page-level granularity only (per the
//! product decision) — no per-panel tracking.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProgressEvent {
    /// UUIDv7, generated by whichever device observed the event.
    pub id: Uuid,
    #[serde(rename = "manga_id")]
    pub publication_id: Uuid,
    #[serde(rename = "chapter_id")]
    pub unit_id: Uuid,
    /// 0-based page within the unit.
    pub page: u32,
    /// Device that produced the event (e.g. `"web"`, `"phone"`).
    pub device: String,
    pub at: DateTime<Utc>,
}

/// Merged current position for a publication (was `Position`). Wire shape
/// stays `{chapter_id, page, at}`: `locations` flattens and the enum is
/// untagged.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Locator {
    #[serde(rename = "chapter_id")]
    pub unit_id: Uuid,
    #[serde(flatten)]
    pub locations: Locations,
    pub at: DateTime<Utc>,
}

/// Where within a unit. Page-based for image kinds (all of this slice);
/// a `Progression` variant arrives with the EPUB slice.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Locations {
    Page { page: u32 },
}

impl Locator {
    /// The page for image-based kinds.
    pub fn page(&self) -> u32 {
        match self.locations {
            Locations::Page { page } => page,
        }
    }
}

/// Pick the winning event according to the journal merge rule.
/// Works on any subset; merging partial journals is associative.
pub fn merge_position<'a, I>(events: I) -> Option<&'a ProgressEvent>
where
    I: IntoIterator<Item = &'a ProgressEvent>,
{
    events
        .into_iter()
        .max_by(|a, b| a.at.cmp(&b.at).then_with(|| a.id.cmp(&b.id)))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ev(id: u128, at_secs: i64, page: u32) -> ProgressEvent {
        ProgressEvent {
            id: Uuid::from_u128(id),
            publication_id: Uuid::from_u128(1),
            unit_id: Uuid::from_u128(2),
            page,
            device: "test".into(),
            at: DateTime::from_timestamp(at_secs, 0).unwrap(),
        }
    }

    #[test]
    fn latest_wins_and_id_breaks_ties() {
        let events = [ev(1, 100, 4), ev(2, 200, 9), ev(3, 200, 7)];
        // 2 and 3 share a timestamp; higher id (3) wins deterministically.
        assert_eq!(merge_position(&events).unwrap().page, 7);

        // Merging winners of partial journals gives the same result
        // (associativity — what offline reconciliation relies on).
        let (a, b) = events.split_at(1);
        let partial = [
            merge_position(a).unwrap().clone(),
            merge_position(b).unwrap().clone(),
        ];
        assert_eq!(merge_position(&partial).unwrap().page, 7);
    }

    #[test]
    fn locator_wire_is_1x_position() {
        let json = r#"{"chapter_id":"00000000-0000-0000-0000-000000000002","page":7,"at":"2026-01-01T00:00:00Z"}"#;
        let l: Locator = serde_json::from_str(json).unwrap();
        assert_eq!(l.page(), 7);
        let out = serde_json::to_value(&l).unwrap();
        assert_eq!(out["chapter_id"], "00000000-0000-0000-0000-000000000002");
        assert_eq!(out["page"], 7);
        assert!(out.get("locations").is_none());
    }
}
